name: Development vuejs Client Deployment
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  deployment_of_hackathon_client_vuejs_to_dev:
    name: Deploy Client Vuejs Dev

    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v6.0.2

      - name: Use Node.js 24
        uses: actions/setup-node@v6.2.0
        with:
          node-version: '24'

      - name: npm install
        run: npm install

      - name: npm run build
        run: npm run build

      - name: rsync deployments
        uses: burnett01/rsync-deployments@8.0.3
        with:
          switches: -avz --no-o --no-g --no-perms --no-t --omit-dir-times --delete --exclude-from='.rsync-exclude'
          path: /public/
          remote_path: ${{ secrets.DEPLOY_PATH_CLIENT_BUILD }}
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_port: ${{ secrets.DEPLOY_PORT }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
          remote_key_pass: ${{ secrets.DEPLOY_KEY_PASS }}

      - name: Test Info Success
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          details: Successful deployment on build https://dev.ownHackathon.de
          webhookUrl: ${{ secrets.WEBHOOK_DISCORD_URL }}
        if: success()

      - name: Test Info Failure
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: error
          details: Failure deployment on build.
          webhookUrl: ${{ secrets.WEBHOOK_DISCORD_URL }}
        if: failure()
